baseURL: https://blog.champ.design/
languageCode: zh

# ç½‘ç«™æ ‡é¢˜
title: champçš„ä¸ªäººåšå®¢

# ä¸»é¢˜é€‰æ‹©
theme: basic

# å¯ç”¨ Emoji è¡¨æƒ…ç¬¦å·ï¼Œæ¯”å¦‚ :smile: ä¼šæ¸²æŸ“ä¸º ğŸ˜„
# å¸¸ç”¨çš„è¡¨æƒ…ä»£ç : https://www.webfx.com/tools/emoji-cheat-sheet/
enableEmoji: true

# å¯ç”¨ .GitInfo å¯¹è±¡
# å¯ç”¨ä¹‹åï¼Œæ¯ä¸ª page éƒ½å¯ä»¥è®¿é—®åˆ° .GitInfo å¯¹è±¡ï¼Œé€šå¸¸ç”¨äºä¿®æ”¹ Lastmod å‚æ•°
enableGitInfo: true

# å¯ç”¨å†…è” shortcodes
enableInlineShortcodes: true

enableMissingTranslationPlaceholders: true

# ç”Ÿæˆ robots.txt æ–‡ä»¶
enableRobotsTXT: true

# Google Analytics tracking ID
googleAnalytics: ""

# Content æ–‡ä»¶é‡Œæ˜¯å¦åŒ…å«ä¸­æ—¥éŸ©æ–‡å­—ï¼Œç”¨äºä¼˜åŒ–æ‘˜è¦ç”Ÿæˆå’Œå­—æ•°ç»Ÿè®¡
hasCJKLanguage: true

# åˆ†é¡µå¤§å°
paginate: 10

# åˆ†é¡µä½¿ç”¨çš„è·¯å¾„åï¼Œæ¯”å¦‚ç¬¬2é¡µçš„è·¯å¾„ä¸º: https://example.com/page/2
paginatePath: "page"

# .Summary æ‘˜è¦åŒ…å«çš„å­—æ•°
summaryLength: 70
